services:
  frameworktester:
    image: andyschulz/frameworktester-nginx:latest
    ports:
      - 3000:80

  chrome:
#    image: selenium/node-chrome:latest
    image: selenium/node-chrome:136.0-20250828
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_CONNECTION_LIMIT_PER_SESSION=1000
      - SE_OPTS=--enable-managed-downloads true
    ports:
      - "5901:5900"
      - "7901:7900"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"


  firefox:
#    image: selenium/node-firefox:latest
    image: selenium/node-firefox:141.0-20250828
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true
    ports:
      - "5902:5900"
      - "7902:7900"


  selenium-hub:
#    image: selenium/hub:latest
    image: selenium/hub:4.35.0
    container_name: selenium-hub
    environment:
      - SE_NODE_CONNECTION_LIMIT_PER_SESSION=1000
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
