plugins {
    id 'groovy-gradle-plugin'
}


dependencies {
    implementation group: "io.freefair.gradle", name: "lombok-plugin", version: "9.7.0"
    implementation group: "io.freefair.gradle", name: "lombok-plugin", version: "9.7.0"
    implementation group: "pl.allegro.tech.build", name:"axion-release-plugin", version: "1.21.4"
    implementation group: "com.diffplug.spotless", name: "spotless-plugin-gradle", version: "8.10.3"

}

repositories {
    gradlePluginPortal()
}
