title: "Thekla4j"
name: Andy Schulz, Test Automation Engineer

remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs

search_enabled: true
color_scheme: dark
enable_copy_code_button: true
has_toc: true
mermaid: true
exclude:
  - reference/*/part_*.*
