source 'https://rubygems.org'


gem "jekyll", "~> 4.3.3"

gem "just-the-docs", "0.10.0" # pinned to the current release
# gem "just-the-docs"        # always download the latest release
gem 'jekyll-mermaid', '~> 1.0'
gem "webrick", "~> 1.8"
gem "wdm", ">= 0.1.0", platforms: [:mingw, :x64_mingw, :mswin]
gem "csv"
gem "base64"
